name: ktlint Check and Review

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ktlint:
    name: Run ktlint and Reviewdog
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v2

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Google Services JSON 파일을 설정
      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json

      # Ktlint 검사 실행
      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      # reviewdog 실행: PR에 코드 품질 리뷰 남기기
      - name: Run reviewdog with ktlint
        uses: reviewdog/reviewdog@v0.13.0
        with:
          name: "ktlint"
          reporter: "github-pr-review"  # GitHub PR 리뷰에 코멘트
          level: "error"  # 에러 수준으로 표시
          filter_mode: "added"  # 추가된 라인에만 적용 (선택 사항)
          fail_on_error: "true"  # 오류가 있으면 GitHub Action을 실패로 처리
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 기본 GitHub 토큰 사용
          command: "cat ./build/reports/ktlint/ktlintCheck.html | reviewdog -f=html"
